### ISSUE TITLE
Purchase -> Bills Currency

### ISSUE THREAD

**Issue by VinChan1990** [andrewdwallo/erpsaas#127]
Good day, for Bill's record payment, unable to do record payment when bill record's currency is not the default currency

Scenario:
My default currency is MYR

Current Bill in USD

<img width="1298" alt="Image" src="https://github.com/user-attachments/assets/a55264f3-4597-4a20-8fd1-b7081786d4fb" />

Edit and try to record payment, no record payment action

<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/06ca56d5-7f76-4653-986c-c460470e38e1" />

For default bill record's currency, which is MYR or RM

<img width="974" alt="Image" src="https://github.com/user-attachments/assets/d11249b0-4d63-47bf-ba3d-0a7a3d135ec8" />

Another suggestion is for global currency exchange settings, because currency exchange rates fluctuated frequently, possible to set exchange rates by period, i:e 1st to 2nd week of April, USD to MYR = 0.2, 3rd to 4th week of April, USD to MYR = 0.4 etc

<img width="984" alt="Image" src="https://github.com/user-attachments/assets/26cd7d74-85c2-4d2f-8944-34f6d40db312" />

**Comment by andrewdwallo** [comment]
Ill check out the Bug here when I get a chance, but have you looked into the Live Currency feature?

**Comment by andrewdwallo** [comment]
Also, I'm not sure if I understand the point of setting exchange rates by period. Historical transaction exchange rates shouldnt be updated usually, and you shouldnt set exchange rates based on future periods.

**Comment by andrewdwallo** [comment]
The currency issue is fixed in latest release

**Comment by vinnchan** [comment]
> Also, I'm not sure if I understand the point of setting exchange rates by period. Historical transaction exchange rates shouldnt be updated usually, and you shouldnt set exchange rates based on future periods.

Hi since we are allow to add currency exchange rates manually at settings there, possible to add in date period for customers to set themselves for each rate, for future records only, so for those customers not using Currency Exchange API, they still have alternatives
